### ISSUE TITLE
Is document correct?

### ISSUE THREAD

**Issue by shibukawa** [PaulAvery/mithril-mdl#6]
Hi, 

I tried your module, but the following code does not work.

``` js
// not working (copied from README)
m.render(document.body, m(Button, {ripple: true, accent: true, raised: true}, 'I am a button!'));
```

The following code is correct, isn't it?

``` js
// work
m.render(document.body, m.component(Button, {ripple: true, accent: true, raised: true}, 'I am a button!'));
```

**Comment by reminyborg** [comment]
For the code from the README to work you need to use the #next branch of mithril. 

``` json
"dependencies": {
  "mithril": "lhorie/mithril.js#next"
}
```

From the changelog of version 2.1:
- m(component, ...args) can now be used as a shorthand for m.component(component, ...args)

**Comment by UhhhWaitWhat** [comment]
Yeah, reminyborg is right, you need to use the `next` branch of mithril. _mithril-mdl_ should actually have it set int the package.json if I'm not mistaken.

Closing this, because we can't really do anything about his up until the next mithril version. If the problem exists even with the next branch, I will be happy to reopen this issue.
